snap: fix kde-neon dependency: --enable-experimental-extensions
Experimental extension 'kde-neon' is required, but not enabled.

Recommended resolution:
This extension may be enabled with the '--enable-experimental-extensions' parameter.
Error while building Dockerfile for brainframe-qt:
The command '/bin/bash -exo pipefail -c snapcraft' returned a non-zero code: 2
Traceback (most recent call last):
  File "package/snap/build_snap.py", line 148, in <module>
    main()
  File "package/snap/build_snap.py", line 59, in main
    image_id = build_image(
  File "package/snap/build_snap.py", line 93, in build_image
    raise DockerBuildError(message)
__main__.DockerBuildError: Error while building Dockerfile for brainframe-qt:
The command '/bin/bash -exo pipefail -c snapcraft' returned a non-zero code: 2