Fix RuntimeError: Error: Not all translations are finished
        Check pylupdate5 -version, somehow 5.14.* works fine, but 5.15.6 causes
        the issue below,

        Updating '/brainframe-qt/brainframe_qt/ui/resources/i18n/brainframe_zh.qm'...
            Generated 273 translation(s) (272 finished and 1 unfinished)
        Traceback (most recent call last):
          File "scripts/compile_qt_resources.py", line 114, in <module>
            main()
          File "scripts/compile_qt_resources.py", line 37, in main
            compile_tr(args.tr_dev)
          File "scripts/compile_qt_resources.py", line 57, in compile_tr
            update_qm_files(qt_project_file, tr_dev)
          File "scripts/compile_qt_resources.py", line 102, in update_qm_files
            raise RuntimeError("Error: Not all translations are finished, but "
        RuntimeError: Error: Not all translations are finished, but translation development is not enabled.