snap: update snapcraft.yaml to use core20 + python3.8
Fix RuntimeError: Error: Not all translations are finished

    Check pylupdate5 -version, somehow 5.14.* works fine, but 5.15.6 causes
    the issue below,

    Updating '/brainframe-qt/brainframe_qt/ui/resources/i18n/brainframe_zh.qm'...
        Generated 273 translation(s) (272 finished and 1 unfinished)
    Traceback (most recent call last):
      File "scripts/compile_qt_resources.py", line 114, in <module>
        main()
      File "scripts/compile_qt_resources.py", line 37, in main
        compile_tr(args.tr_dev)
      File "scripts/compile_qt_resources.py", line 57, in compile_tr
        update_qm_files(qt_project_file, tr_dev)
      File "scripts/compile_qt_resources.py", line 102, in update_qm_files
        raise RuntimeError("Error: Not all translations are finished, but "
    RuntimeError: Error: Not all translations are finished, but translation development is not enabled.

snap: fix kde-neon dependency: --enable-experimental-extensions

    Experimental extension 'kde-neon' is required, but not enabled.

    Recommended resolution:
    This extension may be enabled with the '--enable-experimental-extensions' parameter.
    Error while building Dockerfile for brainframe-qt:
    The command '/bin/bash -exo pipefail -c snapcraft' returned a non-zero code: 2
    Traceback (most recent call last):
      File "package/snap/build_snap.py", line 148, in <module>
        main()
      File "package/snap/build_snap.py", line 59, in main
        image_id = build_image(
      File "package/snap/build_snap.py", line 93, in build_image
        raise DockerBuildError(message)
    __main__.DockerBuildError: Error while building Dockerfile for brainframe-qt:
    The command '/bin/bash -exo pipefail -c snapcraft' returned a non-zero code: 2

snap: fix snapcraft.yaml on ubuntudesktop/gnome-3-38-2004

    According to https://github.com/cibuilds/snapcraft, Ricardo N Feliciano, the auther of
    cibuilds/snapcraft:core20, indicating this change

--no-dev is deprecated by --only main

Entry point needs to be executed directly without 'python3' in apps
section. shebang line is required.